# conda environment description file for the analysis-camryn environment
#
# Create a conda environment in which to run Jupyter Notebooks in this directory with:
#
#   $ conda env create -f environment.yaml
#   $ conda activate analysis-camryn
#
# To add new packages to the environment,
# add them to the dependencies list below,
# then update the activated environment with:
#
#   (analysis-camryn)$ conda env update -f environment.yaml

name: analysis-camryn

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - bottleneck
  - click
  - cliff
  - cmocean
  - coverage
  - dask
  - flox
  - f90nml
  - gsw
  - ipdb
  - ipython
  - jupyterlab
  - lxml
  - matplotlib
  - nbsphinx
  - netCDF4
  - numpy
  - openpyxl
  - pandas
  - pip
  - pytest
  - python=3
  - pytz
  - python-dateutil
  - pyyaml
  - requests
  - retrying
  - rich
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - structlog
  - tqdm
  - xarray
  
  - pip:
    - angles
